apiVersion: apps/v1
kind: Deployment
metadata:
  name: titaniam-deployment
  labels:
    app: titaniam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: titaniam
  template:
    metadata:
      labels:
        app: titaniam
    spec:
      containers:
      - name: titaniam
        image: titaniam/hello-world:1.0
        ports:
        - containerPort: 8080