name: Create Tenant Pipeline
run-name: ${{ github.actor }} is running the create tenant pipeline for the tenant ${{ inputs.tenantName }} 🚀

on:
  workflow_dispatch:
    inputs:
      tenantName:
        description: "Enter the tenant name to be created(Example: titanium). Don't use spaces or special characters"
        required: true
        type: string

env:
  AWS_REGION: ap-south-1
  TF_VAR_tenant_name: ${{ github.event.inputs.tenantName }}

jobs:
  create-tenant-eks:
    name: Create Tenant EKS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Format
        id: format
        run: terraform format

      - name: Terraform Plan
        id: plan
        run: terraform plan
